datasets:
  - name: synthbuster
    type: FileImageDataset
    path: '/mnt/extern/DeepFake/Datasets/Cozzolino_ea_2023/synthbuster'
  - name: 'CIFAKE_test'
    type: FileImageDataset
    path: '/mnt/extern/DeepFake/Datasets/CIFAKE/test'