datasets:
  - name: Synthbuster
    type: FileImageDataset
    path: '/mnt/extern/DeepFake/Datasets/Cozzolino_ea_2023/synthbuster'
  - name: SynthWildX
    type: FileImageDataset
    path: '/mnt/extern/DeepFake/Datasets/Cozzolino_ea_2023/synthWildX'
  - name: CIFAKE-test
    type: FileImageDataset
    path: '/mnt/extern/DeepFake/Datasets/CIFAKE/test'
  - name: FaceForensics++
    type: FileVideoDataset
    path: '/mnt/extern/DeepFake/Datasets/FaceForensics++-dataset/FaceForensics++'
  - name: Cozzolino-test
    type: FileImageDataset
    path: '/mnt/extern/DeepFake/Datasets/Cozzolino_ea_2023/test_set'
  - name: GenImage-val
    type: GenImageDataset
    path: '/mnt/extern/DeepFake/Datasets/GenImage/GenImage'
    split: val