import argparse
import os.path
from typing import Sequence

import confidence
from datasets import tqdm

from deepfake_detection.data import Dataset
from deepfake_detection.evaluation.metrics import accuracy, roc_auc
from deepfake_detection.models import Model, Prediction
from deepfake_detection.utils.configuration import parse_dataset_config, load_model
from deepfake_detection.utils.io import read_predictions_from_file, write_predictions_to_file, get_predictions_filename


def evaluate(dataset_config: str,
             model_config: str,
             output_dir: str,
             predictions_dir: str = None) -> None:
    """
    Evaluates a model on specified datasets and generates metrics and visualizations.

    The function loads datasets specified in a dataset configuration file and a  model from a model configuration file.
    It evaluates the model performance on each dataset, calculates metrics, and generates plots or other evaluative
    outputs. The results are stored in the specified output directory.

    :param dataset_config: File path to the dataset configuration. Can contain one or multiple dataset configurations.
    :param model_config: File path to the model configuration. Should contain configuration for a single model class.
    :param output_dir: Directory path to store evaluation results.
    :param predictions_dir: Directory path where model predictions are cached or stored.
    """
    # Load datasets
    datasets = parse_dataset_config(dataset_config)

    # Load model
    model = load_model(confidence.loadf(model_config))

    # Print evaluation information
    print(f"Evaluating {model.name} model on {len(datasets)} datasets: {[d for d in datasets.keys()]}")

    # Evaluate for each dataset
    for dataset in datasets:

        # Get dataset object
        dataset = datasets[dataset]

        print(f"Evaluating {dataset.name}...")

        # Make or retrieve cached predictions
        predictions = get_predictions(model, dataset, predictions_dir)

        # Calculate metrics / make plots and write to output dir
        evaluate_model_on_dataset(dataset, model, predictions, output_dir)


def get_predictions(model: Model, dataset: Dataset, predictions_dir: str=None) -> Sequence[Prediction]:
    """
    Gets predictions for a given model and dataset, either by generating new predictions or
    loading them from an existing file. If the predictions file does not exist, the function
    will make predictions using the provided model and dataset, then save them to a specified
    directory. If the predictions file already exists, it will load the predictions from the file.
    If no predictions directory is provided, this function will always make predictions without saving them.

    :param model: The model to use for generating predictions.
    :param dataset: The dataset for which predictions are to be made.
    :param predictions_dir: The directory where predictions are stored or should be saved.
                            If not provided, this function will make predictions without saving them.
    :return: A sequence of predictions generated by the model for the given dataset.
    """
    # Get predictions file path
    if predictions_dir:
        predictions_file = os.path.join(predictions_dir, get_predictions_filename(dataset.name, model.name))
    else:
        predictions_file = None

    # If predictions file is not specified or does not yet exist, make predictions
    if predictions_file is None or not os.path.exists(predictions_file):

        predictions = []
        for instance in tqdm(dataset, desc=f"Making predictions for {dataset.name}", total=len(dataset)):

            # Make prediction
            prediction = model.predict(instance)
            predictions.append(prediction)

        # Write predictions to file (if predictions file specified)
        if predictions_file:
            write_predictions_to_file(predictions_dir, predictions, dataset, model.name)
            print(f"Saved predictions to {predictions_file}")
        else:
            print("Skipping saving predictions to file because no predictions directory specified.")

    # Otherwise load predictions from file
    else:
        print(f"Loading predictions from {predictions_file}")
        predictions = read_predictions_from_file(predictions_file)

    return predictions


def evaluate_model_on_dataset(dataset: Dataset,
                              model: Model,
                              predictions: Sequence[Prediction],
                              output_dir: str) -> None:
    """
    Evaluates the performance of a prediction model on a given dataset by computing classification metrics,
    generating outputs, and saving the metrics to a file in the specified directory.

    :param dataset: The dataset object containing the ground truth data.
    :param model: The model to evaluate.
    :param predictions: A sequence of prediction objects corresponding to the dataset.
    :param output_dir: The directory path where the evaluation metrics are to be saved.
    """
    # Classification metrics
    acc = accuracy(dataset, predictions)
    auc = roc_auc(dataset, predictions)

    print("Evaluation results for", dataset.name, ":")
    print(f"Accuracy: {acc}")
    print(f"AUC: {auc}")

    # Make output directory
    os.makedirs(output_dir, exist_ok=True)

    # Save metrics to file
    with open(os.path.join(output_dir, f"{dataset.name}_{model.name}_metrics.txt"), 'w') as f:
        f.write(f"Accuracy: {acc}")
        f.write(f"AUC: {auc}")


if __name__ == '__main__':
    # Define and parse arguments
    parser = argparse.ArgumentParser()
    parser.add_argument('-d','--dataset-config',
                        type=str, required=True, help='Path to dataset config file.')
    parser.add_argument('-m', '--model-config',
                        type=str, required=True, help='Path to model config file.')
    parser.add_argument('-p', '--predictions-dir',
                        default='predictions',
                        type=str, required=False, help='Path to directory where predictions should be saved.')
    parser.add_argument('-o', '--output-dir',
                        default='results',
                        type=str, required=False,
                        help='Path to directory where evaluation predictions should be saved.')
    args = vars(parser.parse_args())

    # Run evaluation
    evaluate(**args)