name: CICD
on:
  # Triggers for any branch
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  # Build
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Flake8 Annotator
        uses: rbialon/flake8-annotations@v1

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - uses: Jimver/cuda-toolkit@v0.2.24
        with:
          cuda: '12.5.0'

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4

      - name: Install dependencies
        run: |
          pdm install
          pdm install -dG test

      - name: Run unit tests
        run: pdm run pytest --import-mode=append tests/

  # Bump version
  release:
    # Only run on main branch
    if: github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1_0fake  # Needed for full commit history

      - name: Python Semantic Release
        uses: python-semantic-release/python-semantic-release@v9.21.0
        with:
          github_token: ${{ secrets.VERSION_BUMP_TOKEN }}